### ISSUE TITLE
Silly question -- but - -how does one USE this? 

### ISSUE THREAD

**Issue by sjmcdowall** [KnisterPeter/vscode-ava-runner#6]
Hi!  I am trying to run my ava tests from within VSCode and installed this extension .. but .. can not for the life of me figure out how to actually make it work or do anything?  I did a "AVA Start" thing .. but .. then what?  I don't see anything changing or a new console / output window, etc. 

What am I  missing?  :)

**Comment by KnisterPeter** [comment]
No question is silly. I don't use this extension myself anymore but to sum it up:

* you need to have ava installed locally in your project (./node_modules/.bin/ava). This is done if you run `npm install ava -D` or `yarn add ava -D`
* If you then run `AVA Start` a process is spawned in the background executing your tests.
* You should see a status bar entry showing the results.

**Comment by sjmcdowall** [comment]
Thanks @KnisterPeter !  Just out of curiosity if you don't use this anymore, what DO you use!? :)

**Comment by KnisterPeter** [comment]
@sjmcdowall Mostly I'm using jest in a terminal and sometimes wallaby in my IDE.

**Comment by sjmcdowall** [comment]
Thanks -- I am interested in why the switch from AVA/NYC to Jest?  And Wallaby ??  I'm just starting with AVA .. so if there are reasons to switch??  (and yes this is getting a bit off topic but it's closed anyway!) :)

**Comment by KnisterPeter** [comment]
@sjmcdowall No particular reason. But here are some maybe reasons:

- The watch mode and its options
- The detection what tests are required to execute
- The possibility to run test across multiple projects

And wallaby is a totally different thing. Its not comparable to jest or ava. Its an awesome IDE integrated test runner (which can run jest and maybe even ava).

**Comment by sjmcdowall** [comment]
Thanks for the great info @KnisterPeter !!  I'll have to "kick some tires" here on these.

**Comment by KnisterPeter** [comment]
Your welcome
