### ISSUE TITLE
Provide documentation on how to use the plugin

### ISSUE THREAD

**Issue by Lukenickerson** [KnisterPeter/vscode-ava-runner#7]
As noted in comments here -- https://marketplace.visualstudio.com/items?itemName=KnisterPeter.vscode-ava-runner#qna -- the README does not provide enough information to get started using this plugin. More descriptive information and steps should be added, as well as a link back to the GitHub repo.

**Comment by KnisterPeter** [comment]
@Lukenickerson I'm sorry but this extension is quite unmaintained right now since I'm not using it anymore.

**Comment by Lukenickerson** [comment]
@KnisterPeter -- Thanks for the update. Do you have any notes on how to get started with it? I might be interested in taking over this project to keep it maintained.

**Comment by KnisterPeter** [comment]
@lukenickerson If you have a bit patience I'm glad to add you as contributor/owner. And I'll get you started. I'm on holiday right now, so I'll need a bit of time for that.
